language: elixir
elixir:
  - 1.3.2
  - 1.4.0
otp_release:
  - 18.2
  - 19.1
matrix:
  # We are only interested on the newest/oldest pair
  exclude:
    - elixir: 1.4.0
      otp_release: 18.2
    - elixir: 1.3.2
      otp_release: 19.1
sudo: required
dist: trusty
cache: apt
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - ECTO_POOL=poolboy mix test
  - ECTO_POOL=sbroker mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - 15023157626@163.com